// 문제 27 : try catch 문을 사용해 예외를 처리하는 코드를 작성하세요.

try {
  console.log(3 + 5);
} catch (error) {
  console.error("실패했습니다.:", error)
}
